# base image source https://github.com/rhdt/EL-Dockerfiles/blob/master/base/python3/Dockerfile

FROM quay.io/openshiftio/rhel-base-python3:latest

COPY ./requirements.txt /

RUN python3 -m pip install --upgrade &&\
    pip3 install -r requirements.txt && rm requirements.txt

COPY ./src /src

ADD scripts/entrypoint.sh /bin/entrypoint.sh

RUN chmod 777 /bin/entrypoint.sh

ENTRYPOINT ["/bin/entrypoint.sh"]
